### PR TITLE
Add workflow file to correct folder

### PR DESCRIPTION
**Pull request by robzolkos**
Moving the ci file to the correct folder where Github Actions expects it.  My bad.

Have you enabled Github Actions to run in settings?

### CODE REVIEW

**Comment by Shpigford** [comment]
> Have you enabled Github Actions to run in settings?

I've shockingly never used Github Actions. What specifically do I need to do on that front to get this working?

**Comment by robzolkos** [comment]
I think these are the main settings to have in place (most are default I think)

CleanShot 2024-01-08 at 12 47 58@2x

**Comment by Shpigford** [comment]
Gotcha. Yeah, those are all already enabled. Merging now and seeing what happens. 🫣

**Comment by robzolkos** [comment]
Cool - I'll work on the errors and PR up fixes shortly.

**Pull request merged**
